"""Centralized error codes for VRP API."""

from enum import Enum


class ErrorCode(Enum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    SOLVER_ERROR = "SOLVER_ERROR"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    SOLUTION_ERROR = "SOLUTION_ERROR"
    INVALID_MATRIX_DATA = "INVALID_MATRIX_DATA"
    INVALID_VEHICLE_DATA = "INVALID_VEHICLE_DATA"
    INVALID_JOB_DATA = "INVALID_JOB_DATA"
    NO_SOLUTION_FOUND = "NO_SOLUTION_FOUND"
    TIME_LIMIT_EXCEEDED = "TIME_LIMIT_EXCEEDED"