"""Centralized error codes for VRP API."""

from enum import Enum


class ErrorCode(Enum):
    INTERNAL_ERROR = "INTERNAL_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    
    VRP_ERROR = "VRP_ERROR"
    SOLVER_ERROR = "SOLVER_ERROR"
    TIMEOUT_ERROR = "TIMEOUT_ERROR"
    
    INVALID_VEHICLE_DATA = "INVALID_VEHICLE_DATA"
    INVALID_JOB_DATA = "INVALID_JOB_DATA"
    INVALID_MATRIX_DATA = "INVALID_MATRIX_DATA"
    CAPACITY_EXCEEDED = "CAPACITY_EXCEEDED"
    INVALID_LOCATION_INDEX = "INVALID_LOCATION_INDEX"
    
    DATABASE_CONNECTION_ERROR = "DATABASE_CONNECTION_ERROR"
    DATABASE_SAVE_ERROR = "DATABASE_SAVE_ERROR"
    DATABASE_QUERY_ERROR = "DATABASE_QUERY_ERROR"
    
    NO_SOLUTION_FOUND = "NO_SOLUTION_FOUND"
    SOLVER_INITIALIZATION_ERROR = "SOLVER_INITIALIZATION_ERROR"
    ROUTE_VALIDATION_ERROR = "ROUTE_VALIDATION_ERROR"
    INVALID_ROUTE_ASSIGNMENT = "INVALID_ROUTE_ASSIGNMENT"
    
    SOLUTION_VALIDATION_ERROR = "SOLUTION_VALIDATION_ERROR"